### ISSUE TITLE
panic: sql: Register called twice for driver postgres when use as a pkg

### ISSUE THREAD

**Issue by felipeweb** [prest/prest#268]
```
panic: sql: Register called twice for driver postgres
goroutine 1 [running]:
database/sql.Register(0xc88d94, 0x8, 0x1118e40, 0x118e820)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/database/sql/sql.go:50 +0x1ad
github.com/nuveo/application.core/vendor/github.com/lib/pq.init.0()
	/home/travis/gopath/src/github.com/nuveo/application.core/vendor/github.com/lib/pq/conn.go:45 +0x5c
github.com/nuveo/application.core/vendor/github.com/lib/pq.init()
	<autogenerated>:1 +0x77d
github.com/nuveo/application.core/vendor/github.com/prest/adapters/postgres/connection.init()
	<autogenerated>:1 +0x58
github.com/nuveo/application.core/vendor/github.com/prest/adapters/postgres.init()
	<autogenerated>:1 +0x91
github.com/nuveo/application.core/instances/ci.init()
	<autogenerated>:1 +0x93
main.init()
	<autogenerated>:1 +0x53
```

**Comment by felipeweb** [comment]
occurs when external pkg  import github.com/prest/adapters/postgres/connection and github.com/prest/adapters/postgres together.
to avoid this problem using an elegant solution we need to nove connection pkg to internal pkg blocking the external pkg imports connection
